version: '3'

networks:
  docker-network:
    driver: bridge

services:
  express-server:
    container_name: express-server
    build: .
    networks:
      - docker-network
    depends_on:
      - session-storage
    environment: 
      - NODE_ENV=development
    ports:
     - 8080:8080
     
  session-storage:
    container_name: session-storage
    image: redis:alpine
    restart: unless-stopped
    tty: true
    ports:
      - 6379:6379
    networks:
      - docker-network
