version: "3"

networks:
  elastic-network:
    driver: bridge

volumes:
  esdata:

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    environment:
      - "cluster.name=es-docker-cluster"
      - "node.name=elastic-search"
      - "network.host=0.0.0.0"
      - "transport.host=0.0.0.0"
      - "xpack.security.enabled=false"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "allow_partial_search_results=true"
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic-network
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1

  appsearch:
    container_name: appsearch
    image: docker.elastic.co/app-search/app-search:7.6.2
    depends_on:
      - elasticsearch
      - kibana
    environment:
      - "app_search.external_url=http://35.202.58.140:3002"
      - "elasticsearch.host=http://elasticsearch:9200"
      - "elasticsearch.username=elastic"
      - "elasticsearch.password=password"
      - "allow_es_settings_modification=true"
      - "secret_management.encryption_keys=[4a2cd3f81d39bf28738c10db0ca782095ffac07279561809eecc722e0c20eb09]"
    networks:
      - elastic-network
    ports:
      - 3002:3002

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      enterpriseSearch.host: "http://appsearch:3002"
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    networks:
      - elastic-network
